syntax = "proto3";

package device;

option go_package = "device-service/proto";

import "google/protobuf/timestamp.proto";

service DeviceService {
  rpc CreateDevice(CreateDeviceRequest) returns (DeviceResponse);
  rpc GetDevice(GetDeviceRequest) returns (DeviceResponse);
  rpc ListDevices(ListDevicesRequest) returns (ListDevicesResponse);
  rpc UpdateDevice(UpdateDeviceRequest) returns (DeviceResponse);
  rpc DeleteDevice(DeleteDeviceRequest) returns (DeleteDeviceResponse);
}

message CreateDeviceRequest {
  string name    = 1;
  string type    = 2;
  string unit    = 3;
  int32  room_id = 4;
}

message GetDeviceRequest {
  int32 id = 1;
}

message ListDevicesRequest {
  string status  = 1;
  int32  room_id = 2;
}

message UpdateDeviceRequest {
  int32  id     = 1;
  string name   = 2;
  string status = 3;
}

message DeleteDeviceRequest {
  int32 id = 1;
}

message DeviceResponse {
  int32  id        = 1;
  string name      = 2;
  string type      = 3;
  string unit      = 4;
  string status    = 5;
  int32  room_id   = 6;
  string room_name = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp updated_at = 9;
}

message ListDevicesResponse {
  repeated DeviceResponse devices = 1;
}

message DeleteDeviceResponse {
  bool success = 1;
}
