// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/telemetry/telemetry.proto

package telemetry

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryService_RecordTelemetry_FullMethodName    = "/telemetry.TelemetryService/RecordTelemetry"
	TelemetryService_GetLatestTelemetry_FullMethodName = "/telemetry.TelemetryService/GetLatestTelemetry"
	TelemetryService_ListTelemetry_FullMethodName      = "/telemetry.TelemetryService/ListTelemetry"
	TelemetryService_CollectFromSensor_FullMethodName  = "/telemetry.TelemetryService/CollectFromSensor"
)

// TelemetryServiceClient is the client API for TelemetryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryServiceClient interface {
	RecordTelemetry(ctx context.Context, in *RecordTelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	GetLatestTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
	ListTelemetry(ctx context.Context, in *ListTelemetryRequest, opts ...grpc.CallOption) (*ListTelemetryResponse, error)
	CollectFromSensor(ctx context.Context, in *CollectFromSensorRequest, opts ...grpc.CallOption) (*TelemetryResponse, error)
}

type telemetryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryServiceClient(cc grpc.ClientConnInterface) TelemetryServiceClient {
	return &telemetryServiceClient{cc}
}

func (c *telemetryServiceClient) RecordTelemetry(ctx context.Context, in *RecordTelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_RecordTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) GetLatestTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_GetLatestTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) ListTelemetry(ctx context.Context, in *ListTelemetryRequest, opts ...grpc.CallOption) (*ListTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_ListTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryServiceClient) CollectFromSensor(ctx context.Context, in *CollectFromSensorRequest, opts ...grpc.CallOption) (*TelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelemetryResponse)
	err := c.cc.Invoke(ctx, TelemetryService_CollectFromSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelemetryServiceServer is the server API for TelemetryService service.
// All implementations must embed UnimplementedTelemetryServiceServer
// for forward compatibility.
type TelemetryServiceServer interface {
	RecordTelemetry(context.Context, *RecordTelemetryRequest) (*TelemetryResponse, error)
	GetLatestTelemetry(context.Context, *GetTelemetryRequest) (*TelemetryResponse, error)
	ListTelemetry(context.Context, *ListTelemetryRequest) (*ListTelemetryResponse, error)
	CollectFromSensor(context.Context, *CollectFromSensorRequest) (*TelemetryResponse, error)
	mustEmbedUnimplementedTelemetryServiceServer()
}

// UnimplementedTelemetryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryServiceServer struct{}

func (UnimplementedTelemetryServiceServer) RecordTelemetry(context.Context, *RecordTelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) GetLatestTelemetry(context.Context, *GetTelemetryRequest) (*TelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) ListTelemetry(context.Context, *ListTelemetryRequest) (*ListTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTelemetry not implemented")
}
func (UnimplementedTelemetryServiceServer) CollectFromSensor(context.Context, *CollectFromSensorRequest) (*TelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectFromSensor not implemented")
}
func (UnimplementedTelemetryServiceServer) mustEmbedUnimplementedTelemetryServiceServer() {}
func (UnimplementedTelemetryServiceServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryServiceServer will
// result in compilation errors.
type UnsafeTelemetryServiceServer interface {
	mustEmbedUnimplementedTelemetryServiceServer()
}

func RegisterTelemetryServiceServer(s grpc.ServiceRegistrar, srv TelemetryServiceServer) {
	// If the following call panics, it indicates UnimplementedTelemetryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryService_ServiceDesc, srv)
}

func _TelemetryService_RecordTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).RecordTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_RecordTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).RecordTelemetry(ctx, req.(*RecordTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_GetLatestTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).GetLatestTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_GetLatestTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).GetLatestTelemetry(ctx, req.(*GetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_ListTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).ListTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_ListTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).ListTelemetry(ctx, req.(*ListTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryService_CollectFromSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectFromSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryServiceServer).CollectFromSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryService_CollectFromSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryServiceServer).CollectFromSensor(ctx, req.(*CollectFromSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TelemetryService_ServiceDesc is the grpc.ServiceDesc for TelemetryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryService",
	HandlerType: (*TelemetryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordTelemetry",
			Handler:    _TelemetryService_RecordTelemetry_Handler,
		},
		{
			MethodName: "GetLatestTelemetry",
			Handler:    _TelemetryService_GetLatestTelemetry_Handler,
		},
		{
			MethodName: "ListTelemetry",
			Handler:    _TelemetryService_ListTelemetry_Handler,
		},
		{
			MethodName: "CollectFromSensor",
			Handler:    _TelemetryService_CollectFromSensor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/telemetry/telemetry.proto",
}
