// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: proto/telemetry/telemetry.proto

package telemetry

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTelemetryRequest) Reset() {
	*x = RecordTelemetryRequest{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTelemetryRequest) ProtoMessage() {}

func (x *RecordTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTelemetryRequest.ProtoReflect.Descriptor instead.
func (*RecordTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *RecordTelemetryRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *RecordTelemetryRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RecordTelemetryRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *GetTelemetryRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

type ListTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTelemetryRequest) Reset() {
	*x = ListTelemetryRequest{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTelemetryRequest) ProtoMessage() {}

func (x *ListTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ListTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *ListTelemetryRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *ListTelemetryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CollectFromSensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectFromSensorRequest) Reset() {
	*x = CollectFromSensorRequest{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectFromSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectFromSensorRequest) ProtoMessage() {}

func (x *CollectFromSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectFromSensorRequest.ProtoReflect.Descriptor instead.
func (*CollectFromSensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *CollectFromSensorRequest) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *CollectFromSensorRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      int32                  `protobuf:"varint,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *TelemetryResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TelemetryResponse) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *TelemetryResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TelemetryResponse) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *TelemetryResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TelemetryResponse   `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTelemetryResponse) Reset() {
	*x = ListTelemetryResponse{}
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTelemetryResponse) ProtoMessage() {}

func (x *ListTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_telemetry_telemetry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ListTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_telemetry_telemetry_proto_rawDescGZIP(), []int{5}
}

func (x *ListTelemetryResponse) GetRecords() []*TelemetryResponse {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_proto_telemetry_telemetry_proto protoreflect.FileDescriptor

const file_proto_telemetry_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/telemetry/telemetry.proto\x12\ttelemetry\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\x16RecordTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\"2\n" +
	"\x13GetTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\"I\n" +
	"\x14ListTelemetryRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"T\n" +
	"\x18CollectFromSensorRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\"\xa5\x01\n" +
	"\x11TelemetryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\x05R\bdeviceId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"O\n" +
	"\x15ListTelemetryResponse\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.telemetry.TelemetryResponseR\arecords2\xe6\x02\n" +
	"\x10TelemetryService\x12R\n" +
	"\x0fRecordTelemetry\x12!.telemetry.RecordTelemetryRequest\x1a\x1c.telemetry.TelemetryResponse\x12R\n" +
	"\x12GetLatestTelemetry\x12\x1e.telemetry.GetTelemetryRequest\x1a\x1c.telemetry.TelemetryResponse\x12R\n" +
	"\rListTelemetry\x12\x1f.telemetry.ListTelemetryRequest\x1a .telemetry.ListTelemetryResponse\x12V\n" +
	"\x11CollectFromSensor\x12#.telemetry.CollectFromSensorRequest\x1a\x1c.telemetry.TelemetryResponseB\x1bZ\x19smarthome/proto/telemetryb\x06proto3"

var (
	file_proto_telemetry_telemetry_proto_rawDescOnce sync.Once
	file_proto_telemetry_telemetry_proto_rawDescData []byte
)

func file_proto_telemetry_telemetry_proto_rawDescGZIP() []byte {
	file_proto_telemetry_telemetry_proto_rawDescOnce.Do(func() {
		file_proto_telemetry_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_telemetry_telemetry_proto_rawDesc), len(file_proto_telemetry_telemetry_proto_rawDesc)))
	})
	return file_proto_telemetry_telemetry_proto_rawDescData
}

var file_proto_telemetry_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_telemetry_telemetry_proto_goTypes = []any{
	(*RecordTelemetryRequest)(nil),   // 0: telemetry.RecordTelemetryRequest
	(*GetTelemetryRequest)(nil),      // 1: telemetry.GetTelemetryRequest
	(*ListTelemetryRequest)(nil),     // 2: telemetry.ListTelemetryRequest
	(*CollectFromSensorRequest)(nil), // 3: telemetry.CollectFromSensorRequest
	(*TelemetryResponse)(nil),        // 4: telemetry.TelemetryResponse
	(*ListTelemetryResponse)(nil),    // 5: telemetry.ListTelemetryResponse
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_proto_telemetry_telemetry_proto_depIdxs = []int32{
	6, // 0: telemetry.TelemetryResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: telemetry.ListTelemetryResponse.records:type_name -> telemetry.TelemetryResponse
	0, // 2: telemetry.TelemetryService.RecordTelemetry:input_type -> telemetry.RecordTelemetryRequest
	1, // 3: telemetry.TelemetryService.GetLatestTelemetry:input_type -> telemetry.GetTelemetryRequest
	2, // 4: telemetry.TelemetryService.ListTelemetry:input_type -> telemetry.ListTelemetryRequest
	3, // 5: telemetry.TelemetryService.CollectFromSensor:input_type -> telemetry.CollectFromSensorRequest
	4, // 6: telemetry.TelemetryService.RecordTelemetry:output_type -> telemetry.TelemetryResponse
	4, // 7: telemetry.TelemetryService.GetLatestTelemetry:output_type -> telemetry.TelemetryResponse
	5, // 8: telemetry.TelemetryService.ListTelemetry:output_type -> telemetry.ListTelemetryResponse
	4, // 9: telemetry.TelemetryService.CollectFromSensor:output_type -> telemetry.TelemetryResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_telemetry_telemetry_proto_init() }
func file_proto_telemetry_telemetry_proto_init() {
	if File_proto_telemetry_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_telemetry_telemetry_proto_rawDesc), len(file_proto_telemetry_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_telemetry_telemetry_proto_goTypes,
		DependencyIndexes: file_proto_telemetry_telemetry_proto_depIdxs,
		MessageInfos:      file_proto_telemetry_telemetry_proto_msgTypes,
	}.Build()
	File_proto_telemetry_telemetry_proto = out.File
	file_proto_telemetry_telemetry_proto_goTypes = nil
	file_proto_telemetry_telemetry_proto_depIdxs = nil
}
